import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/layout/navbar";
import Banner from "@/components/home/banner";
import HowItWorks from "@/components/home/how-it-works";
import Testimonials from "@/components/home/testimonials";
import Faqs from "@/components/home/faq";

export default function Home() {
  return (
    <>
      <Head>
        <title>Educash Flow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-r from-[#0b1220] via-[#1a1f3c] to-primary-dark">
        <Navbar />
        <Banner />
      </div>
      <HowItWorks />
      <Testimonials />
      <Faqs />
    </>
  );
}
