import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/layout/navbar";
import Banner from "@/components/home/banner";
import HowItWorks from "@/components/home/how-it-works";
import Testimonials from "@/components/home/testimonials";
import Faqs from "@/components/home/faq";
import Reward from "@/components/home/reward";
import CssParticles from "@/components/particles";
import BgSvg from "@/components/layout/bg";
 
import connectDB from "@/utils/connectmongo";
import Quiz from "../model/quizCreation"
import UsersQuiz from "@/components/UserQuiz/quiz";
import { useState } from "react";

export default function Home(props) {
const[modal, setModal] = useState(true)
//this for user quiz
const allQuestions = props.quiz


  return (
    <>
      <Head>
        <title>Educash Flow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative bg-gradient-to-r from-[#0b1220] via-[#1a1f3c] to-primary-dark">
        <Navbar />
        <CssParticles />
        <Banner allQuestions={allQuestions} />
        {modal && <UsersQuiz allQuestions={allQuestions} onClose={()=>{setModal(false)}} />}
      </div>
      <div className="relative">
        <HowItWorks />

        <div className="w-full absolute top-24 -z-10">
          <BgSvg />
        </div>
        <Testimonials />
        <Reward />
        <Faqs />
      </div>
    </>
  );
}
export async function getServerSideProps(){
  await connectDB()
  const quiz = await Quiz.find({}).lean()
  
  

  return{
    props:{
      quiz:JSON.parse(JSON.stringify(quiz))
     
    }
  }
}